version: "3.0"
services:
  consul:
    image: consul:1.4.0
    ports:
      - "8500:8500"
  game:
    build: game
    ports:
      - "8080:8080"
    links:
      - "consul"
  recommendation:
    build: recommendation
    links:
      - "consul"

