version: "3.0"
services:
  consul:
    image: consul:1.4.0
    ports:
      - "8500:8500"
  game:
    image: game:latest
    ports:
      - "8080:8080"
    links:
      - "consul"
  recommendation:
    image: recommendation:latest
    links:
      - "consul"
