version: "3.0"
services:
  consul:
    image: consul:1.4.0
    ports:
      - "8500:8500"

  frontend:
    build: "front-end"
    labels:
      traefik.port: 80
      traefik.frontend.rule: "PathPrefix:/"

  game:
    image: game:latest
    links:
      - "consul"
    labels:
      traefik.port: 8080
      traefik.frontend.rule: "PathPrefixStrip:/api/"

  recommendation:
    image: recommendation:latest
    links:
      - "consul"

  reverse_proxy:
    image: traefik:1.7.6
    command:
      - "--api"
      - "--docker"
    ports:
      - "8080:443" # https port (running on port 8080)
      - "81:8080" # web ui (running on port 81)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # ITS IMPORTANT THAT THESE ARE TWO SEPRATE VOLUMES (see https://github.com/containous/traefik/issues/2001)
      - /etc/letsencrypt/live/cityquest.robinvdb.me/cert.pem:/certs/cert.pem
      - /etc/letsencrypt/live/cityquest.robinvdb.me/privkey.pem:/certs/privkey.pem
      - ./traefik.toml:/traefik.toml
