version: "3.0"
services:
  consul:
    image: consul:1.4.0
    ports:
      - "8500:8500"

  frontend:
    build: "front-end"
    labels:
      traefik.port: 80
      traefik.frontend.rule: "PathPrefix:/"

  game:
    image: game:latest
    links:
      - "consul"
    labels:
      traefik.port: 8080
      traefik.frontend.rule: "PathPrefixStrip:/api/"

  recommendation:
    image: recommendation:latest
    links:
      - "consul"

  reverse-proxy:
    image: traefik:1.7.6-alpine
    depends_on:
      - consul
    command:
      - "--api"
      - "--docker"
    ports:
      - "8080:80" # http port (running on port 8080)
      - "81:8080" # web ui (running on port 81)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
