debug = true

logLevel = "DEBUG"
defaultEntryPoints = ["https"]

# The syntax is somewhat esoteric so this is mostly copy-paste
[entryPoints]
    [entryPoints.https]
        address = ":443"
        [entryPoints.https.tls]
            [[entryPoints.https.tls.certificates]]
                certFile = "/certs/cert.pem"
                keyFile = "/certs/privkey.pem"