spring:
  application:
    name: game
  cloud:
    consul:
      host: consul
      port: 8500
      discovery:
        instanceId: ${spring.application.name}:${random.value}
        healthCheckPath: /health
        healthCheckInterval: 20s

server:
  port: 8080
